name: Build and Push Docker Image and Deploy it to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  learning-github-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            server

      - name: Build Docker Image
        run: docker build -t mustafasayyed/snapshop-backend:2.0 ./server

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push mustafasayyed/snapshop-backend:2.0

      - name: Docker Logout
        run: docker logout

      - name: Docker Build and Push completion message
        run: echo "Docker Image Build and Pushed successfully!"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
