name: Testing GitHub Actions

on:
    push: 
        branches:
          - main
        
        
jobs:
  learning-github-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            server
      
      - name: List all the files
        run: ls -la

      - name: Display server directory
        run: ls -ls server

      - name: Check Docker Version
        run: docker --version
      
      - name: Build Docker Image
        run: docker build -t mustafasayyed/snapshop-backend:2.0 ./server


      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push mustafasayyed/snapshop-backend:2.0

      - name: Docker Logout
        run: docker logout

      - name: Completion Message
        run: echo "Docker Image pushed successfully!"
